name: viteconnect
description: Dart library for ViteConnect.
version: 0.0.1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  convert: ^3.0.2
  cryptography: ^2.0.5
  freezed_annotation: ^1.1.0
  json_annotation: ^4.5.0
  stack_trace: ^1.10.0
  uuid: ^3.0.6
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^1.1.1
  json_serializable: ^6.2.0
  lints: ^2.0.0
  test: ^1.21.2

scripts:
  codegen: dart run build_runner build --delete-conflicting-outputs